export const FETCH_BOOKS_REQUEST = "FETCH_BOOKS_REQUEST";
export const FETCH_BOOKS_SUCCESS = "FETCH_BOOKS_SUCCESS";
export const FETCH_BOOKS_ERROR = "FETCH_BOOKS_ERROR";
export const BOOK_ADDED_TO_CART = "BOOK_ADDED_TO_CART";
export const BOOK_REMOVED_TO_CART = "BOOK_REMOVED_TO_CART";
export const ALL_BOOKS_REMOVED_TO_CART = "ALL_BOOKS_REMOVED_TO_CART";
